DROP TABLE IF EXISTS users cascade ;
DROP TABLE IF EXISTS category cascade ;
DROP TABLE IF EXISTS events cascade ;
drop table if exists compilations cascade ;

create table users(
    id integer GENERATED BY DEFAULT AS IDENTITY primary key NOT NULL,
    email varchar(50) NOT NULL ,
    name varchar(50) not null
);

create table category(
    id integer generated by default as identity primary key not null ,
    name varchar(255) not null unique
);

create table events(
    id integer generated by default as identity not null,
    annotation varchar(255) not null,
    confirmedRequests integer,
    category integer references category(id) on delete restrict ,
    createdOn TIMESTAMP,
    description varchar(1000),
    eventDate TIMESTAMP,
    initiator integer references  users (id),
    paid boolean default false,
    participantLimit integer default (0),
    publishedOn TIMESTAMP,
    requestModeration boolean default true,
    title varchar (100),
    views integer,
    lat real,
    lon real,
    state varchar (10)
);
create table compilations(
    id integer generated by default as identity not null,
    pinned boolean,
    title varchar(250)
);