version: '3.1'
services:
  ewm-service:
    build: ./ewm-service
    image: ewm_service_image
    container_name: ewm_service_container
    depends_on:
      - postgres
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/explore_with_me
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - STATS_SERVER_URL=http://stats-server:9090
  stats-server:
    build: ./stats-server
    image: stats_image
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/explore_with_me
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  postgres:
    image: postgres:14-alpine
    container_name: ewm_db
    environment:
      POSTGRES_DB: "explore_with_me"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"