version: '3.1'
services:
  stats-server:
    build: ./Stats-Server
    image: stats_image
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/explore_with_me
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  postgres:
    image: postgres:14-alpine
    container_name: ewm_db
    environment:
      POSTGRES_DB: "explore_with_me"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"