#version: '3.8'
#services:
#
#  stats-server:
#    build: ./stats-server
#    image: stats_image
#    container_name: stats_container
#    ports:
#     - "9090:9090"
#    depends_on:
#     - stats-db
#    environment:
#     - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:6540/stats-db
#     - POSTGRES_DB=stats-db
#     - POSTGRES_USER=postgres
#     - POSTGRES_PASSWORD=iamroot
#
#  stats-db:
#    image: postgres:14-alpine
#    container_name: stats-db
#    ports:
#      - "6540:5432"
#    environment:
#      - POSTGRES_DB=stats-db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=iamroot
#
#  ewm-service:
#    build: ewm-service
#    image: main_server_image
#    container_name: main_server_container
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ewm-db
#      - stats-server
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:6541/ewm-db
#      - POSTGRES_DB=explore_with_me
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=iamroot
#      - STATS_SERVER_URL=http://stats-server:9090
#
#  ewm-db:
#    image: postgres:14-alpine
#    container_name: ewm-db
#    ports:
#      - "6541:5432"
#    environment:
#      - POSTGRES_DB=ewm-db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=iamroot

version: '3.8'
services:
  stats-server:
    build: ./stats-server
    image: stats_image
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: ewm-service
    image: main_server_image
    container_name: main_server_container
    ports:
    - "8080:8080"
    depends_on:
    - ewm-db
    - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore_with_me
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot


  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot