DROP TABLE IF EXISTS users;

create table users(
    id integer generated by default as identity not null,
    email varchar(50) NOT NULL ,
    name varchar(50) not null
);

create table category(
    id integer generated by default as identity not null ,
    name varchar(255) not null
);